language: node_js

node_js:
  - 12.6

services: mongodb

cache:
  directories:
    - node_modules

before_script:
  - npm install

jobs:
  include:
    - stage: lint
      name: "Linting Test"
      script: npm run tslint 
    - stage: compile
      name: "Compile Typescript to Javascript"
      script: npm run ts:compile
    - stage: deploy
      name: "Deploy to Production"
      script: 
        - npm run ts:compile
        - bash ./deploy.sh

branches: 
  only:
    - master